var	data = {
    "name": "Kosciuszko",
    "file": "kosciuszko_all_20x60.ai",
    "baseWidth": 20,
    "baseHeight": 60,
    "monospaced": true,
    "baseLetterSpacing": 28,
    "baseLineHeight": 90,
    "baseLetterSpaceUnit":10,
    "charLetterSpacing": {
	    "a":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "b":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "c":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "d":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "e":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "f":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "g":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "h":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "i":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "j":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "k":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "l":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "m":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "n":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "o":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "p":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "q":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "r":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "s":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "t":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "u":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "v":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "w":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "x":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "y":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "z":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "A":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "B":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "C":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "D":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "E":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "F":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "G":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "H":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "I":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "J":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "K":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "L":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "M":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "N":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "O":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "P":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "Q":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "R":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "S":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "T":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "U":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "V":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "W":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "X":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "Y":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "Z":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "0":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "1":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "2":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "3":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "4":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "5":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "6":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "7":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "8":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "9":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "-":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "—":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "_":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "%":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "&":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "@":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "$":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "?":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "!":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ".":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ",":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "~":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ":":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ";":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "\"":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "“":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "”":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "'":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "’":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "^":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ")":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "(":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ">":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "<":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "}":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "{":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "]":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "[":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "|":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "#":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "=":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "+":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "*":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "\\":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "/":{"sidebearing":[0.5, 0.5], "kerningpairs":{}}
	}
}