var	data = {
    "name": "Troutman",
    "file": "troutman_all_40x60.svg",
    "baseWidth": 40,
    "baseHeight": 60,
    "monospaced": false,
    "baseLetterSpacing": 45,
    "baseLineHeight": 115,
    "baseLetterSpaceUnit":12,
    "charLetterSpacing": {
	    "a":{"sidebearing":[0,0], "kerningpairs":{}},
	    "b":{"sidebearing":[0,-.1], "kerningpairs":{}},
	    "c":{"sidebearing":[0,.06], "kerningpairs":{}},
	    "d":{"sidebearing":[0,-.1], "kerningpairs":{}},
	    "e":{"sidebearing":[0,.01], "kerningpairs":{}},
	    "f":{"sidebearing":[0,-.5], "kerningpairs":{}},
	    "g":{"sidebearing":[0,-0.25], "kerningpairs":{}},
	    "h":{"sidebearing":[0,-.2], "kerningpairs":{}},
	    "i":{"sidebearing":[0,-.1], "kerningpairs":{}},
	    "j":{"sidebearing":[0,-1.5], "kerningpairs":{}},
	    "k":{"sidebearing":[0,-.35], "kerningpairs":{}},
	    "l":{"sidebearing":[0,-.2], "kerningpairs":{}},
	    "m":{"sidebearing":[0,-.25], "kerningpairs":{}},
	    "n":{"sidebearing":[-.2,0], "kerningpairs":{}},
	    "o":{"sidebearing":[0,-.1], "kerningpairs":{}},
	    "p":{"sidebearing":[0,-1.1], "kerningpairs":{}},
	    "q":{"sidebearing":[0,0], "kerningpairs":{}},
	    "r":{"sidebearing":[0,0], "kerningpairs":{}},
	    "s":{"sidebearing":[0,0], "kerningpairs":{}},
	    "t":{"sidebearing":[0,-.55], "kerningpairs":{}},
	    "u":{"sidebearing":[0,0], "kerningpairs":{}},
	    "v":{"sidebearing":[0,-.08], "kerningpairs":{}},
	    "w":{"sidebearing":[0,-.09], "kerningpairs":{}},
	    "x":{"sidebearing":[0,0], "kerningpairs":{}},
	    "y":{"sidebearing":[0,-.25], "kerningpairs":{}},
	    "z":{"sidebearing":[0,0], "kerningpairs":{}},
	    "A":{"sidebearing":[2,-2.3], "kerningpairs":{}},
	    "B":{"sidebearing":[2,0.2], "kerningpairs":{}},
	    "C":{"sidebearing":[-.2,0.8], "kerningpairs":{}},
	    "D":{"sidebearing":[1.2,-1.1], "kerningpairs":{}},
	    "E":{"sidebearing":[0.2,1], "kerningpairs":{}},
	    "F":{"sidebearing":[0.2,-.5], "kerningpairs":{}},
	    "G":{"sidebearing":[-.8,0.2], "kerningpairs":{}},
	    "H":{"sidebearing":[2,-2.29], "kerningpairs":{}},
	    "I":{"sidebearing":[0.4,0.2], "kerningpairs":{}},
	    "J":{"sidebearing":[2,-2.3], "kerningpairs":{}},
	    "K":{"sidebearing":[0.2,0.8], "kerningpairs":{}},
	    "L":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "M":{"sidebearing":[2,-2.0], "kerningpairs":{}},
	    "N":{"sidebearing":[0.9,0.2], "kerningpairs":{}},
	    "O":{"sidebearing":[0.2,1.2], "kerningpairs":{}},
	    "P":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "Q":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "R":{"sidebearing":[.8,-1.1], "kerningpairs":{}},
	    "S":{"sidebearing":[0.4,0.2], "kerningpairs":{}},
	    "T":{"sidebearing":[1,-2], "kerningpairs":{}},
	    "U":{"sidebearing":[0,0.2], "kerningpairs":{}},
	    "V":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "W":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "X":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "Y":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "Z":{"sidebearing":[0.2,0.2], "kerningpairs":{}},
	    "0":{"sidebearing":[0.1,0.1], "kerningpairs":{}},
	    "1":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "2":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "3":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "4":{"sidebearing":[0.1,0.3], "kerningpairs":{}},
	    "5":{"sidebearing":[0.1,0.3], "kerningpairs":{}},
	    "6":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "7":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "8":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "9":{"sidebearing":[0.1,0.5], "kerningpairs":{}},
	    "-":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "—":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "_":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "%":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "&":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "@":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "$":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "?":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "!":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ".":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ",":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "~":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ":":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ";":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "\"":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "“":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "”":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "'":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "’":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "^":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ")":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "(":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    ">":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "<":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "}":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "{":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "]":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "[":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "|":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "#":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "=":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "+":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "*":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "\\":{"sidebearing":[0.5, 0.5], "kerningpairs":{}},
	    "/":{"sidebearing":[0.5, 0.5], "kerningpairs":{}}
	}
}